Nixtus.Plugin.Payments.Paysafe/Controllers/PaymentPaysafeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Nixtus.Plugin.Payments.Paysafe.Models;
using Nop.Core;
using Nop.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nixtus.Plugin.Payments.Paysafe.Controllers
{
    public class PaymentPaysafeController : BasePaymentController
    {
        private readonly ILocalizationService _localizationService;
        private readonly ISettingService _settingService;
        private readonly IStoreService _storeService;
        private readonly IWorkContext _workContext;
        private readonly IPermissionService _permissionService;
        
        public PaymentPaysafeController(ILocalizationService localizationService,
            ISettingService settingService,
            IStoreService storeService,
            IWorkContext workContext,
            IPermissionService permissionService)
        {
            _localizationService = localizationService;
            _settingService = settingService;
            _storeService = storeService;
            _workContext = workContext;
            _permissionService = permissionService;
        }

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var paySafePaymentSettings = _settingService.LoadSetting<PaySafePaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                UseSandbox = paySafePaymentSettings.UseSandbox,
                TransactModeId = Convert.ToInt32(paySafePaymentSettings.TransactMode),
                LocationId = paySafePaymentSettings.LocationId,
                DeveloperId = paySafePaymentSettings.DeveloperId,
                UserId = paySafePaymentSettings.UserId,
                UserApiKey = paySafePaymentSettings.UserApiKey,
                AdditionalFee = paySafePaymentSettings.AdditionalFee,
                AdditionalFeePercentage = paySafePaymentSettings.AdditionalFeePercentage,
                TransactModeValues = paySafePaymentSettings.TransactMode.ToSelectList(),
                ActiveStoreScopeConfiguration = storeScope
            };

            if (storeScope > 0)
            {
                model.UseSandbox_OverrideForStore = _settingService.SettingExists(paySafePaymentSettings, x => x.UseSandbox, storeScope);
                model.TransactModeId_OverrideForStore = _settingService.SettingExists(paySafePaymentSettings, x => x.TransactMode, storeScope);
                model.LocationId_OverrideForStore = _settingService.SettingExists(paySafePaymentSettings, x => x.LocationId, storeScope);
                model.DeveloperId_OverrideForStore = _settingService.SettingExists(paySafePaymentSettings, x => x.DeveloperId, storeScope);
                model.AdditionalFee_OverrideForStore = _settingService.SettingExists(paySafePaymentSettings, x => x.AdditionalFee, storeScope);
                model.AdditionalFeePercentage_OverrideForStore = _settingService.SettingExists(paySafePaymentSettings, x => x.AdditionalFeePercentage, storeScope);
                model.UserId_OverrideForStore = _settingService.SettingExists(paySafePaymentSettings, x => x.UserId, storeScope);
                model.UserApiKey_OverrideForStore = _settingService.SettingExists(paySafePaymentSettings, x => x.UserApiKey, storeScope);
            }

            return View("~/Plugins/Payments.Paysafe/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            //load settings for a chosen store scope
            var storeScope = GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var authorizeNetPaymentSettings = _settingService.LoadSetting<PaySafePaymentSettings>(storeScope);

            //save settings
            authorizeNetPaymentSettings.UseSandbox = model.UseSandbox;
            authorizeNetPaymentSettings.TransactMode = (TransactMode) model.TransactModeId;
            authorizeNetPaymentSettings.LocationId = model.LocationId;
            authorizeNetPaymentSettings.DeveloperId = model.DeveloperId;
            authorizeNetPaymentSettings.AdditionalFee = model.AdditionalFee;
            authorizeNetPaymentSettings.AdditionalFeePercentage = model.AdditionalFeePercentage;
            authorizeNetPaymentSettings.UserId = model.UserId;
            authorizeNetPaymentSettings.UserApiKey = model.UserApiKey;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            _settingService.SaveSettingOverridablePerStore(authorizeNetPaymentSettings, x => x.UseSandbox, model.UseSandbox_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(authorizeNetPaymentSettings, x => x.TransactMode, model.TransactModeId_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(authorizeNetPaymentSettings, x => x.LocationId, model.LocationId_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(authorizeNetPaymentSettings, x => x.DeveloperId, model.DeveloperId_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(authorizeNetPaymentSettings, x => x.AdditionalFee, model.AdditionalFee_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(authorizeNetPaymentSettings, x => x.AdditionalFeePercentage, model.AdditionalFeePercentage_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(authorizeNetPaymentSettings, x => x.UserId, model.UserId_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(authorizeNetPaymentSettings, x => x.UserApiKey, model.UserApiKey_OverrideForStore, storeScope, false);

            //now clear settings cache
            _settingService.ClearCache();

            SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }
    }
}

Nixtus.Plugin.Payments.Paysafe/Views/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
}

@model Nixtus.Plugin.Payments.Paysafe.Models.ConfigurationModel

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="PaymentPaysafe" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSandbox_OverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="LocationId_OverrideForStore" asp-input="LocationId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="LocationId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="LocationId" />
                        <span asp-validation-for="LocationId"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="DeveloperId_OverrideForStore" asp-input="DeveloperId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="DeveloperId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="DeveloperId" />
                        <span asp-validation-for="DeveloperId"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UserId_OverrideForStore" asp-input="UserId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UserId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UserId" />
                        <span asp-validation-for="UserId"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UserApiKey_OverrideForStore" asp-input="UserApiKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UserApiKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UserApiKey" />
                        <span asp-validation-for="UserApiKey"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="TransactModeId_OverrideForStore" asp-input="TransactModeId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="TransactModeId" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="TransactModeId" asp-items="Model.TransactModeValues" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFee_OverrideForStore" asp-input="AdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFee" />
                        <span asp-validation-for="AdditionalFee"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFeePercentage_OverrideForStore" asp-input="AdditionalFeePercentage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFeePercentage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFeePercentage" />
                        <span asp-validation-for="AdditionalFeePercentage"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        &nbsp;
                    </div>
                    <div class="col-md-9">
                        <input type="submit" name="save" class="btn bg-blue" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Nixtus.Plugin.Payments.Paysafe/Views/PaymentInfo.cshtml
@{
    Layout = "";
}
@model Nixtus.Plugin.Payments.Paysafe.Models.PaymentInfoModel

<form>
    <table width="100%" cellspacing="2" cellpadding="1" border="0">
        <tr>
            <td>
                @Html.LabelFor(model => model.CardNumber, false):
            </td>
            <td>
                @Html.TextBoxFor(model => model.CardNumber, new { id = "ccnumber", style = "Width: 165px;", autocomplete = "off", maxlength = 22 })
                    @Html.ValidationMessageFor(model => model.CardNumber)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ExpireMonth, false):
            </td>
            <td>
                @Html.DropDownListFor(model => model.ExpireMonth, Model.ExpireMonths)
                    /
                    @Html.DropDownListFor(model => model.ExpireYear, Model.ExpireYears)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.CardCode, false):
            </td>
            <td>
                @Html.TextBoxFor(model => model.CardCode, new { id = "cvv", style = "Width: 60px;", autocomplete = "off", maxlength = 4 })
                    @Html.ValidationMessageFor(model => model.CardCode)
            </td>
        </tr>
    </table>
</form>